@startuml klondikev8

class Card {
  - suits: String
  - values: String
  - isFaceUp: Boolean
  - deck: Array[52]
  + constructor()
  + toString()
  + flip()
  + createAndShuffleDeck()
}

class Klondike {
  - stock: Stock
  - waste: Waste
  - foundation: Foundation
  - tableau: Tableau
  + constructor()
}

class Stock {
  - cards: Array[Card]
  + constructor()
  + populateStock() 
}

class StockRenderer {
  + static render(stock: Stock)
}

class Tableau {
  - tableaus: Array[[7]]
  + constructor(stock: Stock)
  + receiveCards(stock: Stock) 
  + distributeCards(stock: Stock)
  + canMoveCardToAnotherTableau(cardToMove: Card, destinationTableau: Tableau)
}

class TableauRenderer {
  - tableau: Tableau
  + constructor(tableau: Tableau)
  + renderTableausCards()
}

class Foundation {
  - foundations: Array[[4]]
  + constructor()
  + moveCardToFoundation(card: Card, foundationIndex)
  + isMoveToFoundationValid(card: Card, foundationPile)
  + isNextValueInFoundationInOrder(currentValue, nextValue)
}

class Waste {
  - cards: Array[Card]
  + constructor()
  + receiveCardFromStock(stock: Stock)
  + flipLastCard()
}

class WasteRenderer {
  - waste: Waste
  + constructor(waste: Waste)
  + renderWasteCards()
}

Klondike "1" --> "1" Stock
Klondike "1" --> "1" Waste
Klondike "1" --> "1" Foundation
Klondike "1" --> "1" Tableau
Stock "1" *-- "*" Card
Waste "1" *-- "*" Card
Foundation "1" *-- "*" Card
Tableau "1" *-- "*" Card
StockRenderer ..> Stock : uses
TableauRenderer ..> Tableau : uses
WasteRenderer ..> Waste : uses

@enduml
