@startuml klondikev7,

class Card {
  - suits: String
  - values: String
  - deck: Array[52]
  + createAndShuffleDeck()
}

class Klondike {
  + stock: new Stock()
  + tableau: new Tableau(this.stock)
  + foundation: new Foundation()
  + waste: new Waste()
}

class Stock {
  - cards: Array[Card]
  + constructor()
  + populateStock() 
}

class Tableau {
  - tableaus: Array[[7]]
  + constructor(stock)
  + receiveCards(stock) 
  + distributeCards(stock)
}

class Foundation {
  - foundations: Array[[4]]
  + constructor()
  + moveCardToFoundation()
  + isMoveValid()
  + isNextValueInOrder()
}

class Waste {
  - cards: Array[{}]
  + constructor()

}

Stock "1"  -[dotted]-> "*" Card : Uses
Klondike "1" --> "1" Stock
Klondike "1" --> "1" Waste
Klondike "1" --> "1" Foundation
Klondike "1" --> "1" Tableau

@enduml

